/**
 * Public type exports for @conduit/sdk types module.
 */

export {
  NavigationPhase,
  type NavigationPhaseName,
  type NavigationState,
  type IdleState,
  type NavigatingState,
  type LoadedState,
  type ExtractingState,
  type CompleteState,
  type ErrorState,
  NavigationErrorCode,
  type NavigationErrorCodeType,
  type NavigationError,
  isValidTransition,
  assertValidTransition,
  createIdleState,
  createNavigatingState,
  createLoadedState,
  createExtractingState,
  createCompleteState,
  createErrorState,
} from './navigation';

export {
  OutboundMessageType,
  type OutboundMessageTypeName,
  InboundMessageType,
  type InboundMessageTypeName,
  type InjectScriptMessage,
  type ExtractDOMMessage,
  type WaitForElementMessage,
  type GetCookiesMessage,
  type SetCookiesMessage,
  type EvalExpressionMessage,
  type OutboundMessage,
  type NavigationEventMessage,
  type DOMContentMessage,
  type ElementFoundMessage,
  type ElementTimeoutMessage,
  type CookiesResultMessage,
  type ScriptResultMessage,
  type ScriptErrorMessage,
  type ConsoleLogMessage,
  type PageErrorMessage,
  type InboundMessage,
  type CookieData,
  type WebViewRef,
  type PendingRequest,
  generateMessageId,
  resetMessageCounter,
} from './bridge';
